version: '3'

services: 
  api-1:
    build: 
      context: ./hello-1
      dockerfile: Dockerfile
    command: ['npm', 'start']

  api-2:
    build: 
      context: ./hello-2
      dockerfile: Dockerfile
    command: ['npm', 'start']

  api-3:
    build:
      context: ./hello-3
      dockerfile: Dockerfile
    command: ['npm', 'start']

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on: 
      - api-1
      - api-2
      - api-3
    ports: 
      - 3050:80
    